### ISSUE TITLE
Hmm. No PHP SDK?

### ISSUE THREAD

**Issue by bloggervista** [khalti/khalti-web#3]
Sorry it may seem irrelevant. But many people still use php sdk.  I know you provide api and we can use guzzle but we need php sdk for other framework like code igniter or laravel. I can provide fluent api php based one but it guess it will take too much time. Can you give me details if you provide php sdk or not?

**Comment by manishmodi** [comment]
Hello BloggerVista,
Please check our API Documentation at http://docs.khalti.com
Our web SDK is javascript based, so does not depend much on server side languages. Server side langauge is only used for server to server transaction verification.

We have put PHP example for server to server verification for it. 

Please check and let us know your feedback.

Thanks

**Comment by bloggervista** [comment]
yea i know that example. But there are lots of restrictions. Can you look at stripe. They also have java script based sdk which supports many feature.

**Comment by ludbek** [comment]
We are working on low level packages for popular languages. Ultimately sdks for web, android, iOS and  desktop will use them.

**Comment by bloggervista** [comment]
Yeah It is still in beta stage i didn't know. Sorry to give trouble
